# docker-compose.prod.yml - Configuration pour utiliser l'image depuis Docker Hub
version: '3.8'

services:
  veillebot:
    image: nanandre/veillebot:latest
    container_name: veillebot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # Persister la config de démarrage
      - ./bot-config.json:/app/bot-config.json:rw
      # Optionnel : persister les logs
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - veillebot-network

networks:
  veillebot-network:
    driver: bridge
