name: Keep Render Bot Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # toutes les 10 minutes
  workflow_dispatch:        # permet de lancer manuellement depuis GitHub

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl Render Bot
        run: curl -s https://veillebot.onrender.com/health
